### ISSUE TITLE
2차 중간발표 준비 사항 및 피드백

### ISSUE THREAD

**Issue by hyunsu1004** [hyunsu1004/CRM-project#15]

**Comment by hyunsu1004** [comment]
1. 계획 대비 개발 진행 상황 (프로젝트 일정)

2. 구체적인 개발 상황 (개발 소스 코드, 화면 캡처 등)

3. 문제점 대응 방안 및 개선 전략 (테스트 시나리오)

4. 팀원 역할 분담 및 멘토링

5. 향후 계획 대비 달성 가능성

**Comment by SeHIgh** [comment]
## 교수님 피드백
- 로그인, 회원가입 등과 같이 너무 기본적인 부분에 대해서 부각하는 것 보다 시스템 기능의 차별점을 보여줄 수 있는 형태로 발표할 것
