### ISSUE TITLE
1차 중간 발표 자료

### ISSUE THREAD

**Issue by hyunsu1004** [hyunsu1004/CRM-project#8]
[https://www.canva.com/design/DAGSxkAK95g/unORSdbK5cjsuuO0dYts_g/edit](url)

**Comment by SeHIgh** [comment]
[발표 ppt 자료 (보기 전용)](https://www.canva.com/design/DAGSxkAK95g/TTpQvkYfHMQf6eUW0l_2zw/view?utm_content=DAGSxkAK95g&utm_campaign=designshare&utm_medium=link&utm_source=editor)

**Comment by SeHIgh** [comment]
멘토 회의 전 발표자료 정리본
[canva 웹 슬라이드](https://www.canva.com/design/DAGSxkAK95g/TTpQvkYfHMQf6eUW0l_2zw/view?utm_content=DAGSxkAK95g&utm_campaign=designshare&utm_medium=link&utm_source=editor)

**Comment by SeHIgh** [comment]
중간 발표 1 발표 자료 최종
[웹 발표자료 슬라이드](https://www.canva.com/design/DAGSxkAK95g/TTpQvkYfHMQf6eUW0l_2zw/view?utm_content=DAGSxkAK95g&utm_campaign=designshare&utm_medium=link&utm_source=editor)
